import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={ styles.container }>
      <style jsx>
        { `
          h2 {
            font-size: 38px;
          }

          h3 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */ }
      </Head>

      <main className={ styles.main }>
        <h1 className={ styles.title }>
          <span className="mySpan">Hunting Coder</span>
        </h1>

        <div className={ styles.imageWrap }>
          <Image id={ styles.homeImg } src='/homeImg.jpg' width={ 312 } height={ 208 } />
        </div>

        <p className={ styles.description }>
          A blog for Hunting Coders by a Hunting Coders
        </p>

        <div className="blogs">
          <h2>Latest Blogs</h2>
          <div className="blog-item">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>

          <div className="blog-item">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>

          <div className="blog-item">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>

          <div className="blog-item">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>
        </div>
      </main>


    </div>
  )
}
