import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Dummy from '../components/Dummy'

export default function Home() {
  return (
    <div className={ styles.container }>
      <Dummy />
      <style jsx>
        { `
          .mySpan{
            color: yellow;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={ styles.navbar }>
        <ul className={ styles.navList }>
          <Link href="/"><a><li className={ styles.navItem }>Home</li></a></Link>
          <Link href="/blogs"><a><li className={ styles.navItem }>Blogs</li></a></Link>
          <Link href="/about"><a><li className={ styles.navItem }>About</li></a></Link>
          <Link href="/contact"><a><li className={ styles.navItem }>Contact</li></a></Link>
        </ul>
      </nav>

      <main className={ styles.main }>
        <h1 className={ styles.title }>
          <span className="mySpan dummy">Hunting Coder</span>
        </h1>

        <p className={ styles.description }>
          A blog for Hunting Coders by a Hunting Coders
        </p>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blog-item">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>

          <div className="blog-item">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>

          <div className="blog-item">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>

          <div className="blog-item">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>Javascript is the language used to design logic for the web.</p>
          </div>
        </div>
      </main>

      <footer className={ styles.footer }>
        <div className={ styles.left }>
          <h1 className='mySpan'>Hunting Coder</h1>
        </div>

        <div className={ styles.center }>
          <ul>
            <Link href="/"><a><li className={ styles.navItem }>Home</li></a></Link>
            <Link href="/blogs"><a><li className={ styles.navItem }>Blogs</li></a></Link>
            <Link href="/about"><a><li className={ styles.navItem }>About</li></a></Link>
            <Link href="/contact"><a><li className={ styles.navItem }>Contact</li></a></Link>
          </ul>
        </div>

        <div className={ styles.right }>
          <h2>Follow us on</h2>
        </div>
      </footer>
    </div>
  )
}
